FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-full \
    nginx \
    uwsgi \
    uwsgi-plugin-python3 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN python3 -m venv /app/.venv
RUN /app/.venv/bin/pip install --upgrade pip
RUN /app/.venv/bin/pip install -r requirements.txt

COPY ./ ./

COPY app.nginx /etc/nginx/sites-available/app.nginx
RUN rm -f /etc/nginx/sites-enabled/default
RUN ln -s /etc/nginx/sites-available/app.nginx /etc/nginx/sites-enabled/app.nginx

COPY uwsgi.ini /app/uwsgi.ini
COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 5001

CMD ["/start.sh"]