[uwsgi]
chdir = /app
module = app:app

master = true
processes = 2
threads = 2

socket = /tmp/mediapulse.sock
chmod-socket = 666
vacuum = true

virtualenv = /app/.venv
plugins = python3

die-on-term = true